### ISSUE TITLE
Crash on gmail

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#215]
Originally reported by: **xpeh (Bitbucket: [xpeh](https://bitbucket.org/xpeh))**

---

IMAPClient-1.0.1

```
#!python

imapclient.IMAPClient("imap.googlemail.com", ssl=True)
```

```
#!

Traceback (most recent call last):
  File "imapclient.py", line 16, in <module>
    imap = IMAPClient(host, ssl=True)
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\imapclient.py", line 152, in __init__
    self._imap = self._create_IMAP4()
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\imapclient.py", line 164, in _create_IMAP4
    self._timeout)
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\tls.py", line 153, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "D:\Program Files\programming\Python27\lib\imaplib.py", line 173, in __init__
    self.open(host, port)
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\tls.py", line 159, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\tls.py", line 126, in wrap_socket
    ssl_context = create_default_context()
  File "D:\Program Files\programming\Python27\lib\site-packages\imapclient\tls.py", line 109, in create_default_context
    context.load_verify_locations(cadata=certs)
  File "D:\Program Files\programming\Python27\lib\site-packages\backports\ssl\core.py", line 654, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "D:\Program Files\programming\Python27\lib\site-packages\OpenSSL\SSL.py", line 533, in load_verify_locations
    _raise_current_error()
  File "D:\Program Files\programming\Python27\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []

```

imaplib works fine.

```
#!python

imaplib.IMAP4_SSL("imap.googlemail.com")
```

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/218

**Comment by mjs** [comment]
IMAPClient 2.x will no longer use backports.ssl and pyopenssl. This will avoid this issue. See #217.
