### ISSUE TITLE
Incompatibility with outlook.com on Mac with Python 3.6

### ISSUE THREAD

**Issue by paul-hammant** [mjs/imapclient#236]
```
from imapclient import IMAPClient
server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
```

Barfs like so:

```
$ python3 test.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 201, in _safe_ssl_call
    return getattr(sock, call)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1426, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1174, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 151, in wrap_socket
    newsock = ssl_context.wrap_socket(sock, server_hostname=hostname)
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 676, in wrap_socket
    self.check_hostname)
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 241, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 261, in do_handshake
    _safe_ssl_call(False, self._conn, 'do_handshake')
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 222, in _safe_ssl_call
    raise SSLError(*e.args)
backports.ssl.core.SSLError: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
  File "/usr/local/lib/python3.6/site-packages/imapclient/imapclient.py", line 152, in __init__
    self._imap = self._create_IMAP4()
  File "/usr/local/lib/python3.6/site-packages/imapclient/imapclient.py", line 164, in _create_IMAP4
    self._timeout)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 171, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 197, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 177, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 157, in wrap_socket
    raise imaplib.IMAP4.error("SSL error for %s: %s" % (hostname, err.args[-1]))
imaplib.error: SSL error for imap-mail.outlook.com: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
```

MacOS 10.12.3. Versions of things otherwise:

```
$ python3 --version 
Python 3.6.0
$ pip3 freeze 
asn1crypto==0.22.0
backports.ssl==0.0.9
cffi==1.9.1
cryptography==1.8.1
idna==2.5
IMAPClient==1.0.2
mock==1.3.0
oauthlib==2.0.1
packaging==16.8
pbr==2.0.0
pycparser==2.17
pyOpenSSL==16.2.0
pyparsing==2.2.0
requests==2.13.0
requests-oauth2==0.2.0
requests-oauthlib==0.8.0
selenium==3.0.2
six==1.10.0

```

Python 2.7.13 on the same machine and same script **doesn't** barf.

**Comment by NicolasLM** [comment]
I have the same issue with Python 3.5 and 3.6 on MacOS with `cryptography` 1.8.1 and 1.8.2.

Pinning `cryptography==1.8` "solves" the problem.

**Comment by NicolasLM** [comment]
As often, it was as easy as reading the [fine manual](https://cryptography.io/en/latest/changelog/#id3):
`cryptography 1.8` wheel links against `OpenSSL 1.0.2`
`cryptography >= 1.8.1` wheel links against `OpenSSL 1.1.0`

For newer version of cryptography to work on MacOS:

    brew install openssl@1.1

I believe this issue can be closed as it's not related to imapclient.

**Comment by paul-hammant** [comment]
try/except/wrap and rethrow with a URL to something that could be read by the user/developer ....... is a popular technique for libraries. For example the Selenium project does this in many places.

**Comment by paul-hammant** [comment]
Refiled as #326

**Comment by PythonSmonkey** [comment]
from imapclient import IMAPClient
server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
