### ISSUE TITLE
Check `livetest.test_idle` failure with OVH IMAP account

### ISSUE THREAD

**Issue by mlorant** [mjs/imapclient#261]
Using an OVH e-mail account (server ssl0.ovh.net) with livetest.py, I get one failure:
```
======================================================================
FAIL: test_idle (__main__.TestGeneral)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/workspace/imapclientdev/imapclient/imapclient/livetest.py", line 445, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in []

----------------------------------------------------------------------
```

Since getting accounts on this provider is not free (I believe you need a paid plan or owning a domain name on their services), please assign me to this issue. I will look more closely what is happening.

**Comment by mjs** [comment]
Thank you.

**Comment by mlorant** [comment]
So I tweak the `timeout` parameter of `idle_check` in the test to see of things goes. With `timeout=30` and multiple executions I get this (I stripped tests description/trace to ease reading):

```
$ cmd="python -m imapclient.livetest livetest-ovh.ini TestGeneral.test_idle"; for i in $(seq 6); do $cmd; done

1. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 446, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in [(b'OK', b'Still here')]

Ran 1 test in 9.391s

2. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 446, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in [(b'OK', b'Still here')]

Ran 1 test in 29.409s

3. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 465, in test_idle
    self.assertIn((2, b'EXISTS'), responses)
AssertionError: (2, b'EXISTS') not found in []

Ran 1 test in 32.553s


4. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 446, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in [(b'OK', b'Still here')]

Ran 1 test in 27.453s


5. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 446, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in [(b'OK', b'Still here')]

Ran 1 test in 29.470s


6. -------------------------------------------------------------------
  File "imapclient/imapclient/livetest.py", line 446, in test_idle
    self.assertIn((1, b'EXISTS'), responses)
AssertionError: (1, b'EXISTS') not found in [(b'OK', b'Still here')]

Ran 1 test in 29.398s
```

Server response time is a bit random and I don't even know if it is the `append` that is taking time  to be registered internally or if `idle` is sort of "lagging". The third test seems weird too, since it pass the first assert in 32.5 sec, which is rougly equal to the 2s sleep before idle_check and then 30s of timeout. 

That's all for now. Will investigate more later.

**Comment by NicolasLM** [comment]
From my experience `IDLE` notifications are very often lagging behind, not only with OVH.
