### ISSUE TITLE
TypeError when using starttls over port 143

### ISSUE THREAD

**Issue by rustyautopsy** [mjs/imapclient#303]
If I try to create a TLS connection over port 143 as follows...

```
ssl_context = ssl._create_unverified_context()
server = self.connect(host, 143)
server.debug = True
server.starttls(ssl_context)
server.login(self.accounts[0][0], self.accounts[0][1])
```

connect method added for clarity...

```
kwargs = {'host': host, 'port': port, 'use_uid': True}
        if ssl is not None:
            kwargs['ssl'] = True
        if ssl_context is not None:
            kwargs['ssl_context'] = ssl_context

        try:
            return IMAPClient(**kwargs)
        except Exception as error:
            return error
```

I encounter the following error...

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/travisdolan/python-virtual-envs/email-service/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/travisdolan/Documents/projects/email-service/tests/test_imap/test_imap.py", line 82, in test_authenticating_port_143_tls
    server.login(self.accounts[0][0], self.accounts[0][1])
  File "/Users/travisdolan/python-virtual-envs/email-service/lib/python3.6/site-packages/imapclient/imapclient.py", line 215, in login
    unpack=True,
  File "/Users/travisdolan/python-virtual-envs/email-service/lib/python3.6/site-packages/imapclient/imapclient.py", line 1180, in _command_and_check
    typ, data = meth(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 591, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1191, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1014, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1134, in _get_tagged_response
    self._get_response()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1042, in _get_response
    resp = self._get_line()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1149, in _get_line
    if not line.endswith(b'\r\n'):
TypeError: endswith first arg must be str or a tuple of str, not bytes
```

Am I not setting up the connection correctly?

Thanks in advance.

**Comment by rustyautopsy** [comment]
This issue was resolved by ensuring that I was using `from backports import ssl`. Then setting up the SSLContext object correctly.

So to connect to port 143 and then issue starttls as follows...

```
from backports import ssl

ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
server = IMAPClient(host='xxxxxxxxx', port=143)
server.starttls(ssl_context)
server.login('username', 'password')
server.logout()
```

Self high-five! Or I suppose RTFM a little more ;)

**Comment by mjs** [comment]
Glad you worked it out. Note that we stop using backports.ssl in IMAPClient 2.x. All this should become a little more straightforward.
