### ISSUE TITLE
Certificate mismatch on outlook.com barfs on v1.0.2 but does not barf on v0.13

### ISSUE THREAD

**Issue by paul-hammant** [mjs/imapclient#311]
Code to reproduce (Python 2.7.14 via homebrew, Mac 10.13.1 - 17B48):

```
from imapclient import IMAPClient
server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
```
 v1.0.2 of imapclient it barfs with:

```
$ python2 testoutlook.py 
Traceback (most recent call last):
  File "testoutlook.py", line 2, in <module>
    server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
  File "/usr/local/lib/python2.7/site-packages/imapclient/imapclient.py", line 152, in __init__
    self._imap = self._create_IMAP4()
  File "/usr/local/lib/python2.7/site-packages/imapclient/imapclient.py", line 164, in _create_IMAP4
    self._timeout)
  File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 171, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 173, in __init__
    self.open(host, port)
  File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 177, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 154, in wrap_socket
    raise imaplib.IMAP4.error("certificate error for %s: %s" % (hostname, str(err)))
imaplib.error: certificate error for imap-mail.outlook.com: hostname u'imap-mail.outlook.com' doesn't match u'outlook.com'
```
The older v0.13 of imapclient does not barf at the same line, it works.

**Comment by NicolasLM** [comment]
We will soon release IMAPClient `2.0` which fixes many problems related to SSL.

I'm closing this issue as your snippet runs fine on `master`, so I'm confident this problem will be fixed as soon as we release the changes.

**Comment by mjs** [comment]
FWIW, 0.13 didn't attempt to do certificate validation.
