### ISSUE TITLE
Logging error: KeyError 'Levelname'

### ISSUE THREAD

**Issue by elBradford** [mjs/imapclient#346]
When I have the logging module turned on in my application, I get lots of KeyError: 'Levelname' exceptions from the logging module. 

I am using Python 3.6, imapclient 2.0.0. When I don't use logging in my application, they are not printed to console.

A sample error - there are lots of them and they all look the same:

```KeyError: 'Levelname'
Call stack:
  File "/home/pi/.pyenv/versions/3.6.4/bin/carrierpigeon", line 11, in <module>
    load_entry_point('CarrierPigeon', 'console_scripts', 'carrierpigeon')()
  File "/home/pi/repos/carrierpigeon/carrierpigeon/__main__.py", line 11, in main
    thread_imap.run()
  File "/home/pi/repos/carrierpigeon/carrierpigeon/mail.py", line 28, in run
    print(server.list_folders())
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/site-packages/imapclient/imapclient.py", line 492, in list_folders
    return self._do_list('LIST', directory, pattern)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/site-packages/imapclient/imapclient.py", line 539, in _do_list
    typ, dat = self._imap._simple_command(cmd, directory, pattern)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/imaplib.py", line 1191, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/imaplib.py", line 1014, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/imaplib.py", line 1134, in _get_tagged_response
    self._get_response()
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/imaplib.py", line 1046, in _get_response
    if self._match(self.tagre, resp):
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/imaplib.py", line 1169, in _match
    self._mesg("\tmatched r'%r' => %r" % (cre.pattern, self.mo.groups()))
Message: "\tmatched r'b'(?P<tag>NLCP\\\\d+) (?P<type>[A-Z]+) (?P<data>.*)'' => (b'NLCP2', b'OK', b'Success')"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/home/pi/.pyenv/versions/3.6.4/lib/python3.6/logging/__init__.py", line 391, in format
    return self._fmt % record.__dict__
```

**Comment by NicolasLM** [comment]
Hey,

Can you share your logging configuration as well? I have the feeling that the problem is on your side as the correct name for `Levelname` is `levelname`. See https://docs.python.org/3/library/logging.html#logrecord-attributes

**Comment by elBradford** [comment]
You're right! It was in my logging config. I assumed it was this module because it didn't seem to happen until after I upgraded to 2.0.0 and I misread the stack trace. My bad, sorry for wasting your time, thanks for the great library.
