### ISSUE TITLE
Timestamp Parsing: IndexError: string index out of range

### ISSUE THREAD

**Issue by jsonbank** [mjs/imapclient#347]
Here is the stacktrace:
```python
Traceback (most recent call last):
<REMOVED WHERE WE CALL FETCH>
  File "/var/task/imapclient/imapclient.py", line 1130, in fetch
    return parse_fetch_response(data, self.normalise_times, self.use_uid)
  File "/var/task/imapclient/response_parser.py", line 144, in parse_fetch_response
    msg_data[word] = _convert_ENVELOPE(value, normalise_times)
  File "/var/task/imapclient/response_parser.py", line 177, in _convert_ENVELOPE
    dt = parse_to_datetime(envelope_response[0], normalise=normalise_times)
  File "/var/task/imapclient/datetime_util.py", line 25, in parse_to_datetime
    time_tuple = parsedate_tz(_munge(timestamp))
  File "/usr/lib64/python2.7/email/utils.py", line 210, in parsedate_tz
    return _parsedate_tz(data)
  File "/usr/lib64/python2.7/email/_parseaddr.py", line 90, in parsedate_tz
    if not yy[0].isdigit():
IndexError: string index out of range
```

I will try and find the offending values living on the IMAP server. Since this is reproducible.

**Comment by mjs** [comment]
Hi @jsonbank. If you can provide an example input that causes this, we should be able to fix it.
