### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED python 3.6, but python 2.7 is working

### ISSUE THREAD

**Issue by damiafuentes** [mjs/imapclient#372]
Hey,

`imapObj = IMAPClient('imap-mail.outlook.com')`

That piece of code works for Python 2.7, but gives the following error for Python 3.6. Looks like a bug for that specific version of Python.

```
Traceback (most recent call last):
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/lectures/lecture18/test.py", line 8, in <module>
    imapObj = IMAPClient(HOST)
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/venv/lib/python3.6/site-packages/imapclient/imapclient.py", line 254, in __init__
    self._imap = self._create_IMAP4()
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/venv/lib/python3.6/site-packages/imapclient/imapclient.py", line 289, in _create_IMAP4
    self._timeout)
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/venv/lib/python3.6/site-packages/imapclient/tls.py", line 44, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 197, in __init__
    self.open(host, port)
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/venv/lib/python3.6/site-packages/imapclient/tls.py", line 50, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "/Users/damiafuentes/Documents/UCCS/CS_3030_Python/Lectures/venv/lib/python3.6/site-packages/imapclient/tls.py", line 32, in wrap_socket
    return ssl_context.wrap_socket(sock, server_hostname=host)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

Process finished with exit code 1
```

**Comment by NicolasLM** [comment]
Hi,

It works for me:
```
Python 3.6.1 (default, Apr  4 2017, 21:32:05) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imapclient
>>> client = imapclient.IMAPClient('imap-mail.outlook.com')
>>> client.capabilities()
(b'IMAP4', b'IMAP4REV1', b'AUTH=PLAIN', b'AUTH=XOAUTH2', b'SASL-IR', b'UIDPLUS', b'MOVE', b'ID', b'UNSELECT', b'CHILDREN', b'IDLE', b'NAMESPACE', b'LITERAL+')
```

Your issue is probably related to your Python and SSL installation.

**Comment by damiafuentes** [comment]
Can you try with Python 3.6.5? 

How do I fix the `SSL installation` for `Python 3.6.5`? I tried with the new version of `Python 3.7.2` and I run the `Install Certificates.command` file that comes with it and it doesn't work neither.  It gives me the same error.

**Comment by mjs** [comment]
Which 2.7 version of Python are you using? Python versions before 2.7.9 were very lax about certificate validation. It might be that it's working for you with 2.7 because you're using an older version which isn't actually checking the SSL cert.

Things are probably not working for you with Python 3 because Python isn't able to find CA certs to work with. How was Python 3 installed? Is it the system OS X version or was it via Homebrew or something else?

**Comment by damiafuentes** [comment]
It was installed using the DMG file downloaded from www.python.org. How do I fix the SSL cert?

**Comment by damiafuentes** [comment]
Hey @mjs. Can you help me with this, please? I have tried a lot of things and I don't know what to do. Looks like my certificate is not installing good. What can I do?

**Comment by NicolasLM** [comment]
@damiafuentes your issue is outside the scope of imapclient. You should continue this discussion with the team responsible for the Mac build of Python.

Here is a small snippet to reproduce the issue without imapclient:
```python
import socket
import ssl

hostname = 'www.python.org'
context = ssl.create_default_context()

with socket.create_connection((hostname, 443)) as sock:
    with context.wrap_socket(sock, server_hostname=hostname) as ssock:
        print(ssock.version())
```

**Comment by mjs** [comment]
If the above test work for you, please also try replacing the hostname with imap-mail.outlook.com` and the port (443) with 993.
