### ISSUE TITLE
IMAPClient does not work with Office 365 (IMAP)

### ISSUE THREAD

**Issue by devlocalca** [mjs/imapclient#391]
I have a domain hosted on Office 365.

I have working code that will connect to an outlook account :    <user_name>@outlook.com.

**Here is my code:** 

```
from imapclient import IMAPClient
username = '<user_name>@<mydomain>.com'
password = '<password>'
imap_server = 'outlook.office365.com'

client = IMAPClient(imap_server)
client.login(username, password)
```

When I substitute the <user_name>@mydomain.com and password, I get an error:

```
Traceback (most recent call last):
  File "C:\apps\python\3.8.0\Lib\site-packages\imapclient\imapclient.py", line 338, in login
    rv = self._command_and_check(
  File "C:\apps\python\3.8.0\Lib\site-packages\imapclient\imapclient.py", line 1538, in _command_and_check
    typ, data = meth(*args)
  File "C:\apps\python\3.8.0\lib\imaplib.py", line 603, in login
    raise self.error(dat[-1])
imaplib.error: b'LOGIN failed.'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/dev/repos/email-processing/src/python/test/outlook/imap/account/test_inspect_account.py", line 19, in <module>
    client.login(username,  password)
  File "C:\apps\python\3.8.0\Lib\site-packages\imapclient\imapclient.py", line 345, in login
    raise exceptions.LoginError(str(e))
imapclient.exceptions.LoginError: b'LOGIN failed.'

Process finished with exit code 1
```

---
The IMAP server for Office 365 is the same as Outlook, and when going to seetings under the 365 account, I can see that they are the same:

```
Server:    outlook.office365.com
Port: 993
Encryption: TLS
```

Given that the code is working OK with Outlook, but not my own Office 365 hosted domain, does anyone have a clue of what might be going on here?

There is no toggle/switch anywhere to 'enable IMAP', it's enabled by default as I understand.

---

I am cutting/pasting the password from my password manager, just as I do when I login through the web interface, so am absolutely sure that the password is correct,

and I am absolutely sure the <user_name> is correct, checked it thrice.

---

I have also tried pure imaplib code and get the same failure.  There is nothing wrong with my code, but something else is going on here underneath, but I don't know what.

---
**Turning on additional logging, I see:**

```
2020-01-06 23:46:14,670 - DEBUG: Connected to host outlook.office365.com over SSL/TLS
2020-01-06 23:46:14,671 - DEBUG: > b'OENM1 LOGIN **REDACTED**
2020-01-06 23:46:15,164 - DEBUG: < b'OENM1 NO LOGIN failed.'
2020-01-06 23:46:15,164 - DEBUG: 	matched b'(?P<tag>OENM\\d+) (?P<type>[A-Z]+) (?P<data>.*)' => (b'OENM1', b'NO', b'LOGIN failed.')
2020-01-06 23:46:15,164 - DEBUG: NO response: b'LOGIN failed.'
```

**Comment by KristobalJunta** [comment]
Are you sure that your credentials do work and/or you don't have 2FA enabled? As I am using the same method to get messages from Outlook365 right now with the latest lib version, and it works fine.

**Comment by akvadrako** [comment]
It's probably 2FA and not using a special app password for IMAP.

**Comment by mjs** [comment]
What @akvadrako says sounds right to me. If 2FA is enabled there will be some mechanism to create a separate password that can be used for accessing your account via IMAP.

It's also worth noting that Microsoft is moving towards enforcing OAUTH2 for IMAP access: https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/
