### ISSUE TITLE
TypeError: open() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by dandrei** [mjs/imapclient#415]
Hello,

This is the code I am attempting to run:

    import ssl
    import imapclient

    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    imap_client = imapclient.IMAPClient(host='outlook.office365.com', ssl=True, ssl_context=context, port=993)

I get the following stack trace:

    Traceback (most recent call last):
      File "main.py", line 23, in <module>
        main()
      File "main.py", line 8, in main
        imap_client = imapclient.IMAPClient(host='outlook.office365.com', ssl=True, ssl_context=context, port=993)
      File "venv\lib\site-packages\imapclient\imapclient.py", line 254, in __init__
        self._imap = self._create_IMAP4()
      File "venv\lib\site-packages\imapclient\imapclient.py", line 288, in _create_IMAP4
        return tls.IMAP4_TLS(self.host, self.port, self.ssl_context,
      File "venv\lib\site-packages\imapclient\tls.py", line 44, in __init__
        imaplib.IMAP4.__init__(self, host, port)
      File "C:\Python39\lib\imaplib.py", line 202, in __init__
        self.open(host, port, timeout)
    TypeError: open() takes 3 positional arguments but 4 were given

Using:

IMAPClient `2.1.0`
Windows `10`
Python `3.9`

**Comment by NicolasLM** [comment]
Hello, this has been fixed in #413 but it is not released yet. You will have to use `master` on Python 3.9 for now.

**Comment by mjs** [comment]
FYI, this is fixed in the recent 2.2.0 release.
