### ISSUE TITLE
Incompatible with Python 3.9?  open() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by antsol20** [mjs/imapclient#425]
Python 3.9 and 3.9.1 produce the below error
TypeError: open() takes 3 positional arguments but 4 were given

```
>>> from imapclient import IMAPClient
>>> server = IMAPClient('outlook.office365.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Antony\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\imapclient.py", line 254, in __init__
    self._imap = self._create_IMAP4()
  File "C:\Users\Antony\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\imapclient.py", line 288, in _create_IMAP4
    return tls.IMAP4_TLS(self.host, self.port, self.ssl_context,
  File "C:\Users\Antony\AppData\Local\Programs\Python\Python39\lib\site-packages\imapclient\tls.py", line 44, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "C:\Users\Antony\AppData\Local\Programs\Python\Python39\lib\imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
TypeError: open() takes 3 positional arguments but 4 were given
```

**Comment by mjs** [comment]
Fixed in #421
