### ISSUE TITLE
Occasional IMAP exception I'm unable to catch

### ISSUE THREAD

**Issue by smontanaro** [mjs/imapclient#427]
I just moved an app from imaplib to IMAPClient. It's gone well so far, but I occasionally see an exception I'm unable to catch. (I'm talking to Gmail, BTW.) The traceback (two, actually) looks like this:

> Exception in thread imap-thread:
> Traceback (most recent call last):
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/imaplib.py", line 1022, in _command_complete
>     typ, data = self._get_tagged_response(tag, expect_bye=logout)
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/imaplib.py", line 1148, in _get_tagged_response
>     self._get_response()
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/imaplib.py", line 1050, in _get_response
>     resp = self._get_line()
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/imaplib.py", line 1160, in _get_line
>     raise self.abort('socket error: EOF')
> imaplib.abort: socket error: EOF
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "src/polly.py", line 436, in read_imap
>     self.read_loop()
>   File "src/polly.py", line 473, in read_loop
>     result = server.fetch([uid], [b'RFC822'])
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/site-packages/imapclient/imapclient.py", line 1367, in fetch
>     typ, data = self._imap._command_complete("FETCH", tag)
>   File "/home/skip/miniconda3/envs/python38/lib/python3.8/imaplib.py", line 1024, in _command_complete
>     raise self.abort('command: %s => %s' % (name, val))
> imaplib.abort: command: FETCH => socket error: EOF

My code does its IMAP work in a separate thread, which is where I'm trying to catch exceptions:

>                 try:
>                     result = server.fetch([uid], [b'RFC822'])
>                 except imaplib.IMAP4.abort as abt:
>                     self.log.error("%s uid=%s", abt, uid)
>                     raise

but I think I'm missing something. I suspect that either imaplib.abort as reported in the traceback messages is not the same as imaplib.IMAP4.abort or the imapclient code itself is running in another thread.

The full code is here: https://github.com/smontanaro/polly/blob/master/src/polly.py

**Comment by smontanaro** [comment]
Eh, never mind. Just realized I stuck a re-raise in there for debugging then forgot about it... Stupid flub.
