### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

### ISSUE THREAD

**Issue by lin11daddy** [mjs/imapclient#461]
I use imapclient to connect imap server.
The code was successful to run before.
And when I using same code to do some work today, there shows SSLEOFError.
Can who help me fix this problem?

code like this:

context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
client = IMAPClient(host=imap_server, port=imap_port, ssl=True, ssl_context=context)

**Comment by lin11daddy** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linchenhui/.local/lib/python3.9/site-packages/imapclient/imapclient.py", line 284, in __init__
    self._imap = self._create_IMAP4()
  File "/home/linchenhui/.local/lib/python3.9/site-packages/imapclient/imapclient.py", line 321, in _create_IMAP4
    return tls.IMAP4_TLS(
  File "/home/linchenhui/.local/lib/python3.9/site-packages/imapclient/tls.py", line 44, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/lib/python3.9/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "/home/linchenhui/.local/lib/python3.9/site-packages/imapclient/tls.py", line 52, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "/home/linchenhui/.local/lib/python3.9/site-packages/imapclient/tls.py", line 32, in wrap_socket
    return ssl_context.wrap_socket(sock, server_hostname=host)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

**Comment by mjs** [comment]
Which port are you connecting to? This kind of error can happen when you try to talk TLS to a non-TLS port.

If you don't mind providing the service/host you're connecting to, that would be useful too (if it's on the public internet).

**Comment by mjs** [comment]
Closing this due to lack of activity. Please reopen if you can supply more details.
