### ISSUE TITLE
IMAP4_TLS.open() error

### ISSUE THREAD

**Issue by solarmcpanel** [mjs/imapclient#500]
Any suggestions as to what is going on below? Help appreciated!

I'm entering the following in to IDLE shell.
>>>imapObj = imapclient.IMAPClient('imap.virginmedia.com', ssl=True)

I get the following error:-
Traceback (most recent call last):
  File "<pyshell#43>", line 1, in <module>
    imapObj = imapclient.IMAPClient('imap.virginmedia.com', port=993, ssl=True, use_uid=True)
  File "C:\Users\dougl\AppData\Roaming\Python\Python310\site-packages\imapclient\imapclient.py", line 254, in __init__
    self._imap = self._create_IMAP4()
  File "C:\Users\dougl\AppData\Roaming\Python\Python310\site-packages\imapclient\imapclient.py", line 288, in _create_IMAP4
    return tls.IMAP4_TLS(self.host, self.port, self.ssl_context,
  File "C:\Users\dougl\AppData\Roaming\Python\Python310\site-packages\imapclient\tls.py", line 44, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "C:\Users\dougl\AppData\Local\Programs\Python\Python310\lib\imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
TypeError: IMAP4_TLS.open() takes 3 positional arguments but 4 were given

**Comment by axoroll7** [comment]
Installed from pip or github ?

**Comment by mjs** [comment]
I'm not able to replicate this. I can see in the traceback that you're using Python 3.10. Which version of IMAPClient are you using?

**Comment by solarmcpanel** [comment]
Thanks mjs, I'd like to close this thread, I solved it awhile ago, from memory I think it was a version issue.I'm a  bit  new to this, how do I close the thread?Thanks for your time!DougOn 19 Aug 2023 04:56, Menno Finlay-Smits ***@***.***> wrote:
I'm not able to replicate this. I can see in the traceback that you're using Python 3.10. Which version of IMAPClient are you using?

**Comment by mjs** [comment]
No problems. Thanks for circling back.
