### ISSUE TITLE
Consider dropping support for End-of-Life Python 3.6

### ISSUE THREAD

**Issue by JohnVillalovos** [mjs/imapclient#512]
I see this error and doesn't seem that easy to fix. Though the unit tests still pass.

But still wouldn't hurt to drop Python 3.6, in my opinion. Users can still use the previous versions of `imapclient`

FYI: Python 3.6 and Python 3.7 are both End-of-Life: https://devguide.python.org/versions/

```
$ tox -e py36 -r
py36: remove tox env folder /home/dev-user/imapclient/.tox/py36
py36: install_deps> python -I -m pip install -r /home/dev-user/imapclient/requirements-dev.txt
py36: commands[0]> python -m unittest
Error processing line 1 of /home/dev-user/imapclient/.tox/py36/lib/python3.6/site-packages/_virtualenv.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/dev-user/imapclient/.tox/py36/lib/python3.6/site-packages/_virtualenv.py", line 3
      from __future__ import annotations
                                       ^
  SyntaxError: future feature annotations is not defined

Remainder of file ignored
Error processing line 1 of /home/dev-user/imapclient/.tox/py36/lib/python3.6/site-packages/_virtualenv.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/dev-user/imapclient/.tox/py36/lib/python3.6/site-packages/_virtualenv.py", line 3
      from __future__ import annotations
                                       ^
  SyntaxError: future feature annotations is not defined

Remainder of file ignored
...........................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 267 tests in 0.069s

OK
  py36: OK (7.82=setup[7.66]+cmd[0.15] seconds)
  congratulations :) (7.88 seconds)
```

**Comment by NicolasLM** [comment]
Sounds reasonable to me.

**Comment by mjs** [comment]
I'm happy to drop Python 3.6 at this stage too
