### ISSUE TITLE
idle_check can see incomplete lines

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#519]
From #464:

I've found something else that may be related: I connected with tls=FALSE and ran a network capture to see what was actually on the wire. I'm seeing these errors now:

```
Traceback (most recent call last):
  File "./debug-protocol-error.py", line 23, in <module>
    responses = server.idle_check(timeout=30)
  File "/home/david/.local/lib/python3.8/site-packages/imapclient/imapclient.py", line 175, in wrapper
    return func(client, *args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/imapclient/imapclient.py", line 940, in idle_check
    line = self._imap._get_line()
  File "/usr/lib/python3.8/imaplib.py", line 1164, in _get_line
    raise self.abort('socket error: unterminated line: %r' % line)
imaplib.IMAP4.abort: socket error: unterminated line: b'* 91 FETCH (FLAGS (\\Deleted \\Seen \\Recent)'
```

In the network capture, there are two packets which are re-assembled to form the message seen in the error. The only thing in the second packet is \r\n. I have not looked at the code here but is it possible that it's attempting to process a packet that hasn't been fully assembled, which presumably would be in imaplib judging from the trace?

**Comment by mjs** [comment]
The issue is likely that IMAPClient is using imaplib.IMAP4's _get_line while the socket is in non-blocking mode which it isn't really designed for. IMAPClient will like need to call IMAP4.readline() do end of line handling itself instead

**Comment by axoroll7** [comment]
`readline` should return a complete line. I am afraid there could be others unknown side-effects. _imaplib2_ uses its own line reader for this.

Since there is no concurrency, why using non-blocking sockets instead of blocking sockets with timeout ? I don't know why it was originally written this way. Maybe it was necessary in older python versions. Maybe concurrency was the next step. But can this be reconsidered today ?

**Comment by mjs** [comment]
My memory is fuzzy but I'm pretty sure it was done like this because timeouts weren't available with older Python versions. I'm definitely open to rethinking the whole approach to IDLE now that we are only concerned with more modern Python version.s

**Comment by axoroll7** [comment]
A draft :
```python3
def idle_check(self, timeout=None):
    sock:socket.socket = self.socket()

    # make the socket non-blocking so the timeout can be
    # implemented for this call
    sock.settimeout(None)
    sock.setblocking(0)

    self._idle_raw_buffer:bytearray = bytearray()
    self._idle_raw_lines_buffer:List[bytes] = []
    self._idle_parsed_lines_buffer:List[Any] = []

    if timeout is None:
        end = float("inf")
    else:
        end = time.monotonic() + float(timeout)

    try:
        resps = []
        while True:
            timeout = end - time.monotonic()
            if timeout < 0:
                break
            elif timeout == float("inf"):
                timeout = None
            try:
                rlist = select.select([sock], [], [], timeout)[0]
            except (IOError,socket.error):
                break
            if not rlist:
                break
            buf = sock.recv(4096)
            while True:
                newline_pos = buf.find(b"\n")
                if newline_pos > -1:
                    l_buf = buf[:newline_pos]
                    r_buf = buf[newline_pos:]
                    buf = r_buf
                    self._idle_raw_buffer += l_buf
                    line = bytes(self._idle_raw_buffer)
                    self._idle_raw_lines_buffer.append(line)
                    self._idle_raw_buffer.clear()
                else:
                    break
            self._idle_raw_buffer += buf
        while len(self._idle_raw_lines_buffer)>0:
            line = self._idle_raw_lines_buffer[0]
            self._idle_parsed_lines_buffer.append(_parse_untagged_response(line))
            self._idle_raw_lines_buffer.pop(0)
        while len(self._idle_parsed_lines_buffer)>0:
            line = self._idle_raw_lines_buffer.pop(0)
            resps.append(line)
        return resps
    finally:
        sock.setblocking(1)
        self._set_read_timeout()
```

Not tested.

`_idle_raw_buffer`, `_idle_raw_lines_buffer` and `_idle_parsed_lines_buffer` for easier unit tests, for now.

Non-blocking socket utilized, because I was afraid to use blocking socket and being confronted with something new.

Custom line reader, seems ok for me.

Removed `poll` to only use `select`, easier to maintain.

**Comment by axoroll7** [comment]
@mjs 

Should I continue in this direction ? Should I do `idle_done` too, or not, because blocking sockets are better, because they are easier ? Have you already started on your side, and should I stop ? I am open to suggestions.

**Comment by axoroll7** [comment]
https://github.com/python/cpython/issues/51571

I don't have time to look it up, but it seems a `readline` can discard data. The issue is not closed. A non-blocking socket seems safer.

**Comment by mjs** [comment]
Thanks for digging into this @axoroll7 . I don't have anything significant in progress for this so if you want to continue with solving this please go ahead.

I do wonder if we can get away from using non-blocking sockets and use a custom line reading function with a socket timeout. We could side step the issues with readline by implementing it ourselves.

**Comment by mjs** [comment]
Heads up: I've got a rough prototype working which simply uses timeouts. I'll try to get it tidied up for review over the weekend.
