### ISSUE TITLE
SELECT Unsafe Login

### ISSUE THREAD

**Issue by luiox** [mjs/imapclient#544]
Hi, I use the code that in README.rst. I filled in the correct email address, username, and password for the code, but an error occurred.
Here is my code. I can guarantee that my username and password are correct, and I have used an authorization code instead.
![image](https://github.com/mjs/imapclient/assets/70513915/ba2c0f14-824a-42f6-89db-fb80ef984b16)
When I ran these codes, the error 'SELECT Unsafe Login' occurred. I need help.
Traceback (most recent call last):
  File "D:\WorkSpace\InfoSearcher\src\email\email_rewrite.py", line 6, in <module>
    client.select_folder('INBOX')
  File "D:\WorkSpace\InfoSearcher\venv\Lib\site-packages\imapclient\imapclient.py", line 811, in select_folder
    self._command_and_check("select", self._normalise_folder(folder), readonly)
  File "D:\WorkSpace\InfoSearcher\venv\Lib\site-packages\imapclient\imapclient.py", line 1739, in _command_and_check
    self._checkok(command, typ, data)
  File "D:\WorkSpace\InfoSearcher\venv\Lib\site-packages\imapclient\imapclient.py", line 1745, in _checkok
    self._check_resp("OK", command, typ, data)
  File "D:\WorkSpace\InfoSearcher\venv\Lib\site-packages\imapclient\imapclient.py", line 1619, in _check_resp
    raise exceptions.IMAPClientError(
imaplib.IMAP4.error: select failed: SELECT Unsafe Login. Please contact kefu@188.com for help

**Comment by zhangjiale2020** [comment]
https://blog.csdn.net/jony_online/article/details/108638571
看看这篇文章能否解决你的问题
